from dataclasses import dataclass
import random
from typing import List


@dataclass
class Film:
    film_id: int
    thumbnail_image_src: str
    film_title: str


@dataclass
class Season:
    season_id: int
    film_id: int
    season_number: int
    summary: str
    release_year: int
    average_rating: float
    thumbnail_image_src: str


@dataclass
class Episode:
    episode_id: int
    film_season_id: int
    episode_number: int
    episode_title: str
    thumbnail_image_src: str


# List of films in Python (converted from TypeScript)
films = [
    Film(
        film_id=1,
        thumbnail_image_src="https://touchcinema.com/storage/phim-ke-danh-cap-giac-mo/phim-ke-danh-cap-giac-mo.jpg",
        film_title="Inception",
    ),
    Film(
        film_id=2,
        thumbnail_image_src="https://substackcdn.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fbucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com%2Fpublic%2Fimages%2F58af398c-d206-446e-a587-bfff4449d94c_704x396.jpeg",
        film_title="The Godfather",
    ),
    Film(
        film_id=3,
        thumbnail_image_src="https://d1jqhvzwrc220t.cloudfront.net/media/blog/800x450_5.webp",
        film_title="The Dark Knight",
    ),
    Film(
        film_id=4,
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_WiCDscohAM2TnmUX65VwEYBbO-YZ0IvSA2hT9ofyfMHTVnUwXX5hr5h_BipI24_Zu0Q&usqp=CAU",
        film_title="Pulp Fiction",
    ),
    Film(
        film_id=5,
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQO_TClh7CqMdS2ky-YJTkXzZZtcS1OMejeDs9T26C0YBJUMb_t3HSPRpqVz-ag8NBUYDY&usqp=CAU",
        film_title="Fight Club",
    ),
    Film(
        film_id=6,
        thumbnail_image_src="https://cdn.quotesgram.com/img/21/93/1351081511-1994_forrest_gump_1.jpg",
        film_title="Forrest Gump",
    ),
    Film(
        film_id=7,
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQm_-j_N9fIpunypxUaOK-XHj51kxiEsxINGA&s",
        film_title="The Matrix",
    ),
    Film(
        film_id=8,
        thumbnail_image_src="https://mir-s3-cdn-cf.behance.net/projects/404/b96064178494413.Y3JvcCwxNDk4LDExNzEsMCw4NzU.png",
        film_title="Interstellar",
    ),
    Film(
        film_id=9,
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLElDkJXrpyc09Z28q15C0olBZvvpAwR9_ZQ&s",
        film_title="Gladiator",
    ),
    Film(
        film_id=10,
        thumbnail_image_src="https://lecinemaparadiso.co.uk/uploads/THE%20SHAWSHANK%20REDEMPTION%20image.jpg",
        film_title="The Shawshank Redemption",
    ),
    # Series
    Film(
        film_id=11,
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKBHwXxZbJX733TLoYhEibdwG23aNp9vWRxCVcKPKk_TC_GVcz2emKTjkXGLKJ0xwasDg&usqp=CAU",
        film_title="Breaking Bad",
    ),
    Film(
        film_id=12,
        thumbnail_image_src="https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1105420/capsule_616x353.jpg?t=1700810767",
        film_title="Game of Thrones",
    ),
    Film(
        film_id=13,
        thumbnail_image_src="https://res.klook.com/image/upload/u_activities:hnnmfj2oqtp1azxoh1l3,w_1.0,ar_4:3,c_scale,e_blur:10000/c_fill,w_750,h_500/q_80/w_80,x_15,y_15,g_south_west,l_Klook_water_br_trans_yhcmh3/activities/hnnmfj2oqtp1azxoh1l3.jpg",
        film_title="Stranger Things",
    ),
    Film(
        film_id=14,
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPviGBB6hW_MEzfW2pj7-qgbaxP3_hPVKA8A&s",
        film_title="The Witcher",
    ),
    Film(
        film_id=15,
        thumbnail_image_src="https://images.thedirect.com/media/article_full/mandalorian-pedro-pascal-season-3.jpg",
        film_title="The Mandalorian",
    ),
    Film(
        film_id=16,
        thumbnail_image_src="https://resizing.flixster.com/c5XeWe5kfWQjpGyL2-fzQY4Upb4=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p13398828_b_h10_aa.jpg",
        film_title="The Crown",
    ),
    Film(
        film_id=17,
        thumbnail_image_src="https://uniathenaprods3.uniathena.com/s3fs-public/insights-article/seriesreview-e2-80-9cfriends-e2-80-9d_0.jpg",
        film_title="Friends",
    ),
    Film(
        film_id=18,
        thumbnail_image_src="https://resizing.flixster.com/8nJUFmVSfYuWfAA6LVmGqJc4UH8=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p8992561_b_h10_aa.jpg",
        film_title="Sherlock",
    ),
    Film(
        film_id=19,
        thumbnail_image_src="https://upload.wikimedia.org/wikipedia/en/2/28/Westworld_season_1.png",
        film_title="Westworld",
    ),
    Film(
        film_id=20,
        thumbnail_image_src="https://upload.wikimedia.org/wikipedia/en/a/ae/The_Office_Season_8.jpg",
        film_title="The Office",
    ),
]

# List of seasons in Python (converted from TypeScript)
seasons = [
    # Example data for seasons. Please replace with actual data as needed.
    # Breaking Bad Season 1
    Season(
        season_id=1,
        film_id=11,
        season_number=1,
        summary="High school chemistry teacher Walter White turns to manufacturing methamphetamine after a terminal cancer diagnosis, leading to a dramatic transformation.",
        release_year=2008,
        average_rating=9.5,
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKBHwXxZbJX733TLoYhEibdwG23aNp9vWRxCVcKPKk_TC_GVcz2emKTjkXGLKJ0xwasDg&usqp=CAU",
    ),
    # Breaking Bad Season 2
    Season(
        season_id=2,
        film_id=11,
        season_number=2,
        summary="Walter and Jesse's meth operation grows, leading to increased risks and complications as they navigate the criminal underworld.",
        release_year=2009,
        average_rating=9.5,
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKBHwXxZbJX733TLoYhEibdwG23aNp9vWRxCVcKPKk_TC_GVcz2emKTjkXGLKJ0xwasDg&usqp=CAU",
    ),
    # Breaking Bad Season 3
    Season(
        season_id=3,
        film_id=11,
        season_number=3,
        summary="As Walter White's criminal empire grows, he faces escalating threats from law enforcement and rival drug dealers, leading to a dramatic confrontation.",
        release_year=2010,
        average_rating=9.6,
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKBHwXxZbJX733TLoYhEibdwG23aNp9vWRxCVcKPKk_TC_GVcz2emKTjkXGLKJ0xwasDg&usqp=CAU",
    ),
    # Game of Thrones Season 1
    Season(
        season_id=4,
        film_id=12,
        season_number=1,
        summary="Noble families vie for control of the Iron Throne in the Seven Kingdoms of Westeros, leading to political intrigue and epic battles.",
        release_year=2011,
        average_rating=9.3,
        thumbnail_image_src="https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1105420/capsule_616x353.jpg?t=1700810767",
    ),
    # Game of Thrones Season 2
    Season(
        season_id=5,
        film_id=12,
        season_number=2,
        summary="The struggle for power continues with new alliances and conflicts, as the War of the Five Kings threatens to engulf Westeros.",
        release_year=2012,
        average_rating=9.0,
        thumbnail_image_src="https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1105420/capsule_616x353.jpg?t=1700810767",
    ),
    # Game of Thrones Season 3
    Season(
        season_id=6,
        film_id=12,
        season_number=3,
        summary="The battle for the Iron Throne intensifies with new alliances and betrayals, culminating in one of the most shocking events in Westeros.",
        release_year=2013,
        average_rating=9.1,
        thumbnail_image_src="https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1105420/capsule_616x353.jpg?t=1700810767",
    ),
    # Stranger Things Season 1
    Season(
        season_id=7,
        film_id=13,
        season_number=1,
        summary="A group of kids in a small town uncover supernatural events and government conspiracies while searching for their missing friend.",
        release_year=2016,
        average_rating=8.8,
        thumbnail_image_src="https://res.klook.com/image/upload/u_activities:hnnmfj2oqtp1azxoh1l3,w_1.0,ar_4:3,c_scale,e_blur:10000/c_fill,w_750,h_500/q_80/w_80,x_15,y_15,g_south_west,l_Klook_water_br_trans_yhcmh3/activities/hnnmfj2oqtp1azxoh1l3.jpg",
    ),
    # Stranger Things Season 2
    Season(
        season_id=8,
        film_id=13,
        season_number=2,
        summary="The gang continues to confront the Upside Down while dealing with new challenges and changes in their relationships.",
        release_year=2017,
        average_rating=8.7,
        thumbnail_image_src="https://res.klook.com/image/upload/u_activities:hnnmfj2oqtp1azxoh1l3,w_1.0,ar_4:3,c_scale,e_blur:10000/c_fill,w_750,h_500/q_80/w_80,x_15,y_15,g_south_west,l_Klook_water_br_trans_yhcmh3/activities/hnnmfj2oqtp1azxoh1l3.jpg",
    ),
    # Stranger Things Season 3
    Season(
        season_id=9,
        film_id=13,
        season_number=3,
        summary="The Hawkins gang faces a new threat from the Upside Down while dealing with their own personal challenges and changes as they grow older.",
        release_year=2019,
        average_rating=8.9,
        thumbnail_image_src="https://res.klook.com/image/upload/u_activities:hnnmfj2oqtp1azxoh1l3,w_1.0,ar_4:3,c_scale,e_blur:10000/c_fill,w_750,h_500/q_80/w_80,x_15,y_15,g_south_west,l_Klook_water_br_trans_yhcmh3/activities/hnnmfj2oqtp1azxoh1l3.jpg",
    ),
    # The Witcher Season 1
    Season(
        season_id=10,
        film_id=14,
        season_number=1,
        summary="Geralt of Rivia, a monster hunter, navigates the complex political landscape of the Continent while battling supernatural threats.",
        release_year=2019,
        average_rating=8.0,
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPviGBB6hW_MEzfW2pj7-qgbaxP3_hPVKA8A&s",
    ),
    # The Witcher Season 2
    Season(
        season_id=11,
        film_id=14,
        season_number=2,
        summary="Geralt's journey continues as he faces new threats and deepens his involvement with the magical world and its political intrigues.",
        release_year=2021,
        average_rating=7.9,
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPviGBB6hW_MEzfW2pj7-qgbaxP3_hPVKA8A&s",
    ),
    # The Witcher Season 3
    Season(
        season_id=12,
        film_id=14,
        season_number=3,
        summary="Geralt faces new foes and allies as he navigates the complex politics and sorcery of the Continent, with destiny playing a crucial role in his journey.",
        release_year=2023,
        average_rating=8.2,
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPviGBB6hW_MEzfW2pj7-qgbaxP3_hPVKA8A&s",
    ),
    # The Mandalorian Season 1
    Season(
        season_id=13,
        film_id=15,
        season_number=1,
        summary="A lone bounty hunter in the outer reaches of the galaxy takes on a mission that changes his life forever, leading to unexpected adventures.",
        release_year=2019,
        average_rating=8.8,
        thumbnail_image_src="https://images.thedirect.com/media/article_full/mandalorian-pedro-pascal-season-3.jpg",
    ),
    # The Mandalorian Season 2
    Season(
        season_id=14,
        film_id=15,
        season_number=2,
        summary="The Mandalorian continues his quest to return the Child to its kind, facing new threats and forming new alliances along the way.",
        release_year=2020,
        average_rating=8.9,
        thumbnail_image_src="https://images.thedirect.com/media/article_full/mandalorian-pedro-pascal-season-3.jpg",
    ),
    # The Mandalorian Season 3
    Season(
        season_id=15,
        film_id=15,
        season_number=3,
        summary="Din Djarin's quest takes him across the galaxy as he uncovers secrets about Grogu's past and confronts new threats in the Star Wars universe.",
        release_year=2023,
        average_rating=8.8,
        thumbnail_image_src="https://images.thedirect.com/media/article_full/mandalorian-pedro-pascal-season-3.jpg",
    ),
    # The Crown Season 1
    Season(
        season_id=16,
        film_id=16,
        season_number=1,
        summary="The Crown follows the reign of Queen Elizabeth II, exploring the political and personal challenges she faced during the early years of her rule.",
        release_year=2016,
        average_rating=8.7,
        thumbnail_image_src="https://resizing.flixster.com/c5XeWe5kfWQjpGyL2-fzQY4Upb4=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p13398828_b_h10_aa.jpg",
    ),
    # The Crown Season 2
    Season(
        season_id=17,
        film_id=16,
        season_number=2,
        summary="The Crown continues to explore the personal and political life of Queen Elizabeth II, focusing on key events and changes in the British monarchy.",
        release_year=2017,
        average_rating=8.6,
        thumbnail_image_src="https://resizing.flixster.com/c5XeWe5kfWQjpGyL2-fzQY4Upb4=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p13398828_b_h10_aa.jpg",
    ),
    # The Crown Season 3
    Season(
        season_id=18,
        film_id=16,
        season_number=3,
        summary="The Crown delves into the political and social changes of the 1960s and 1970s, highlighting Queen Elizabeth II's evolving role during this period.",
        release_year=2019,
        average_rating=8.8,
        thumbnail_image_src="https://resizing.flixster.com/c5XeWe5kfWQjpGyL2-fzQY4Upb4=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p13398828_b_h10_aa.jpg",
    ),
    # Friends Season 1
    Season(
        season_id=19,
        film_id=17,
        season_number=1,
        summary="The lives of six friends living in New York City, navigating the ups and downs of their personal and professional lives.",
        release_year=1994,
        average_rating=8.9,
        thumbnail_image_src="https://uniathenaprods3.uniathena.com/s3fs-public/insights-article/seriesreview-e2-80-9cfriends-e2-80-9d_0.jpg",
    ),
    # Friends Season 2
    Season(
        season_id=20,
        film_id=17,
        season_number=2,
        summary="The friends continue their adventures, facing new challenges in their relationships and careers while maintaining their close-knit bond.",
        release_year=1995,
        average_rating=9.0,
        thumbnail_image_src="https://uniathenaprods3.uniathena.com/s3fs-public/insights-article/seriesreview-e2-80-9cfriends-e2-80-9d_0.jpg",
    ),
    # Friends Season 3
    Season(
        season_id=21,
        film_id=17,
        season_number=3,
        summary="The group of friends deals with personal growth and the complexities of their relationships as they navigate new challenges.",
        release_year=1996,
        average_rating=9.1,
        thumbnail_image_src="https://uniathenaprods3.uniathena.com/s3fs-public/insights-article/seriesreview-e2-80-9cfriends-e2-80-9d_0.jpg",
    ),
    # Sherlock Season 1
    Season(
        season_id=22,
        film_id=18,
        season_number=1,
        summary="Modern-day adaptation of Sherlock Holmes, with a brilliant detective solving crimes in contemporary London.",
        release_year=2010,
        average_rating=9.0,
        thumbnail_image_src="https://resizing.flixster.com/8nJUFmVSfYuWfAA6LVmGqJc4UH8=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p8992561_b_h10_aa.jpg",
    ),
    # Sherlock Season 2
    Season(
        season_id=23,
        film_id=18,
        season_number=2,
        summary="Sherlock Holmes continues his investigations in modern London, facing new adversaries and complex cases.",
        release_year=2012,
        average_rating=9.1,
        thumbnail_image_src="https://resizing.flixster.com/8nJUFmVSfYuWfAA6LVmGqJc4UH8=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p8992561_b_h10_aa.jpg",
    ),
    # Sherlock Season 3
    Season(
        season_id=24,
        film_id=18,
        season_number=3,
        summary="Sherlock Holmes faces new challenges and old enemies in the highly anticipated return of the modern-day detective series.",
        release_year=2014,
        average_rating=9.0,
        thumbnail_image_src="https://resizing.flixster.com/8nJUFmVSfYuWfAA6LVmGqJc4UH8=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p8992561_b_h10_aa.jpg",
    ),
    # Westworld Season 1
    Season(
        season_id=25,
        film_id=19,
        season_number=1,
        summary="A futuristic theme park populated by artificial beings offers a unique experience for visitors, leading to unforeseen consequences.",
        release_year=2016,
        average_rating=8.6,
        thumbnail_image_src="https://upload.wikimedia.org/wikipedia/en/2/28/Westworld_season_1.png",
    ),
    # Westworld Season 2
    Season(
        season_id=26,
        film_id=19,
        season_number=2,
        summary="The park's inhabitants continue to grapple with their evolving consciousness and the implications of their existence.",
        release_year=2018,
        average_rating=8.5,
        thumbnail_image_src="https://upload.wikimedia.org/wikipedia/en/2/28/Westworld_season_1.png",
    ),
    # Westworld Season 3
    Season(
        season_id=27,
        film_id=19,
        season_number=3,
        summary="The narrative expands beyond the park as the hosts and humans face new challenges in a rapidly changing world.",
        release_year=2020,
        average_rating=8.4,
        thumbnail_image_src="https://upload.wikimedia.org/wikipedia/en/2/28/Westworld_season_1.png",
    ),
    # The Office Season 1
    Season(
        season_id=28,
        film_id=20,
        season_number=1,
        summary="A mockumentary-style series that captures the everyday lives of office employees working at Dunder Mifflin.",
        release_year=2005,
        average_rating=8.7,
        thumbnail_image_src="https://upload.wikimedia.org/wikipedia/en/a/ae/The_Office_Season_8.jpg",
    ),
    # The Office Season 2
    Season(
        season_id=29,
        film_id=20,
        season_number=2,
        summary="The employees of Dunder Mifflin continue their comedic and often awkward interactions while navigating the ups and downs of office life.",
        release_year=2006,
        average_rating=8.8,
        thumbnail_image_src="https://upload.wikimedia.org/wikipedia/en/a/ae/The_Office_Season_8.jpg",
    ),
    # The Office Season 3
    Season(
        season_id=30,
        film_id=20,
        season_number=3,
        summary="The office dynamics shift as new challenges arise and the employees face both personal and professional changes.",
        release_year=2007,
        average_rating=8.7,
        thumbnail_image_src="https://upload.wikimedia.org/wikipedia/en/a/ae/The_Office_Season_8.jpg",
    ),
    Season(
        season_id=31,
        film_id=1,
        season_number=1,
        summary="A placeholder summary for this film.A placeholder summary for this film.A placeholder summary for this film.A placeholder summary for this film.",
        release_year=2017,
        average_rating=8,
        thumbnail_image_src="https://touchcinema.com/storage/phim-ke-danh-cap-giac-mo/phim-ke-danh-cap-giac-mo.jpg",
    ),
    Season(
        season_id=32,
        film_id=2,
        season_number=1,
        summary="A placeholder summary for this film.A placeholder summary for this film.A placeholder summary for this film.A placeholder summary for this film.",
        release_year=2000,
        average_rating=2,
        thumbnail_image_src="https://substackcdn.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fbucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com%2Fpublic%2Fimages%2F58af398c-d206-446e-a587-bfff4449d94c_704x396.jpeg",
    ),
    Season(
        season_id=33,
        film_id=3,
        season_number=1,
        summary="A placeholder summary for this film.A placeholder summary for this film.A placeholder summary for this film.A placeholder summary for this film.",
        release_year=2013,
        average_rating=4,
        thumbnail_image_src="https://d1jqhvzwrc220t.cloudfront.net/media/blog/800x450_5.webp",
    ),
    Season(
        season_id=34,
        film_id=4,
        season_number=1,
        summary="A placeholder summary for this film.A placeholder summary for this film.A placeholder summary for this film.A placeholder summary for this film.",
        release_year=2014,
        average_rating=10,
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_WiCDscohAM2TnmUX65VwEYBbO-YZ0IvSA2hT9ofyfMHTVnUwXX5hr5h_BipI24_Zu0Q&usqp=CAU",
    ),
    Season(
        season_id=35,
        film_id=5,
        season_number=1,
        summary="A placeholder summary for this film.A placeholder summary for this film.A placeholder summary for this film.A placeholder summary for this film.",
        release_year=2009,
        average_rating=8,
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQO_TClh7CqMdS2ky-YJTkXzZZtcS1OMejeDs9T26C0YBJUMb_t3HSPRpqVz-ag8NBUYDY&usqp=CAU",
    ),
    Season(
        season_id=36,
        film_id=6,
        season_number=1,
        summary="A placeholder summary for this film.A placeholder summary for this film.A placeholder summary for this film.A placeholder summary for this film.",
        release_year=2009,
        average_rating=6,
        thumbnail_image_src="https://cdn.quotesgram.com/img/21/93/1351081511-1994_forrest_gump_1.jpg",
    ),
    Season(
        season_id=37,
        film_id=7,
        season_number=1,
        summary="A placeholder summary for this film.A placeholder summary for this film.A placeholder summary for this film.A placeholder summary for this film.",
        release_year=2023,
        average_rating=4,
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQm_-j_N9fIpunypxUaOK-XHj51kxiEsxINGA&s",
    ),
    Season(
        season_id=38,
        film_id=8,
        season_number=1,
        summary="A placeholder summary for this film.A placeholder summary for this film.A placeholder summary for this film.A placeholder summary for this film.",
        release_year=2015,
        average_rating=8,
        thumbnail_image_src="https://mir-s3-cdn-cf.behance.net/projects/404/b96064178494413.Y3JvcCwxNDk4LDExNzEsMCw4NzU.png",
    ),
    Season(
        season_id=39,
        film_id=9,
        season_number=1,
        summary="A placeholder summary for this film.A placeholder summary for this film.A placeholder summary for this film.A placeholder summary for this film.",
        release_year=2014,
        average_rating=5,
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLElDkJXrpyc09Z28q15C0olBZvvpAwR9_ZQ&s",
    ),
    Season(
        season_id=40,
        film_id=10,
        season_number=1,
        summary="A placeholder summary for this film.A placeholder summary for this film.A placeholder summary for this film.A placeholder summary for this film.",
        release_year=2006,
        average_rating=9,
        thumbnail_image_src="https://lecinemaparadiso.co.uk/uploads/THE%20SHAWSHANK%20REDEMPTION%20image.jpg",
    ),
]

episodes = [
    Episode(
        episode_id=1,
        film_season_id=1,
        episode_number=1,
        episode_title="Tập 1",
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKBHwXxZbJX733TLoYhEibdwG23aNp9vWRxCVcKPKk_TC_GVcz2emKTjkXGLKJ0xwasDg&usqp=CAU",
    ),
    Episode(
        episode_id=2,
        film_season_id=1,
        episode_number=2,
        episode_title="Tập 2",
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKBHwXxZbJX733TLoYhEibdwG23aNp9vWRxCVcKPKk_TC_GVcz2emKTjkXGLKJ0xwasDg&usqp=CAU",
    ),
    Episode(
        episode_id=3,
        film_season_id=1,
        episode_number=3,
        episode_title="Tập 3",
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKBHwXxZbJX733TLoYhEibdwG23aNp9vWRxCVcKPKk_TC_GVcz2emKTjkXGLKJ0xwasDg&usqp=CAU",
    ),
    Episode(
        episode_id=4,
        film_season_id=1,
        episode_number=4,
        episode_title="Tập 4",
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKBHwXxZbJX733TLoYhEibdwG23aNp9vWRxCVcKPKk_TC_GVcz2emKTjkXGLKJ0xwasDg&usqp=CAU",
    ),
    Episode(
        episode_id=5,
        film_season_id=2,
        episode_number=1,
        episode_title="Tập 1",
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKBHwXxZbJX733TLoYhEibdwG23aNp9vWRxCVcKPKk_TC_GVcz2emKTjkXGLKJ0xwasDg&usqp=CAU",
    ),
    Episode(
        episode_id=6,
        film_season_id=2,
        episode_number=2,
        episode_title="Tập 2",
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKBHwXxZbJX733TLoYhEibdwG23aNp9vWRxCVcKPKk_TC_GVcz2emKTjkXGLKJ0xwasDg&usqp=CAU",
    ),
    Episode(
        episode_id=7,
        film_season_id=2,
        episode_number=3,
        episode_title="Tập 3",
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKBHwXxZbJX733TLoYhEibdwG23aNp9vWRxCVcKPKk_TC_GVcz2emKTjkXGLKJ0xwasDg&usqp=CAU",
    ),
    Episode(
        episode_id=8,
        film_season_id=3,
        episode_number=1,
        episode_title="Tập 1",
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKBHwXxZbJX733TLoYhEibdwG23aNp9vWRxCVcKPKk_TC_GVcz2emKTjkXGLKJ0xwasDg&usqp=CAU",
    ),
    Episode(
        episode_id=9,
        film_season_id=3,
        episode_number=2,
        episode_title="Tập 2",
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKBHwXxZbJX733TLoYhEibdwG23aNp9vWRxCVcKPKk_TC_GVcz2emKTjkXGLKJ0xwasDg&usqp=CAU",
    ),
    Episode(
        episode_id=10,
        film_season_id=3,
        episode_number=3,
        episode_title="Tập 3",
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKBHwXxZbJX733TLoYhEibdwG23aNp9vWRxCVcKPKk_TC_GVcz2emKTjkXGLKJ0xwasDg&usqp=CAU",
    ),
    Episode(
        episode_id=11,
        film_season_id=3,
        episode_number=4,
        episode_title="Tập 4",
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKBHwXxZbJX733TLoYhEibdwG23aNp9vWRxCVcKPKk_TC_GVcz2emKTjkXGLKJ0xwasDg&usqp=CAU",
    ),
    Episode(
        episode_id=12,
        film_season_id=4,
        episode_number=1,
        episode_title="Tập 1",
        thumbnail_image_src="https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1105420/capsule_616x353.jpg?t=1700810767",
    ),
    Episode(
        episode_id=13,
        film_season_id=4,
        episode_number=2,
        episode_title="Tập 2",
        thumbnail_image_src="https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1105420/capsule_616x353.jpg?t=1700810767",
    ),
    Episode(
        episode_id=14,
        film_season_id=4,
        episode_number=3,
        episode_title="Tập 3",
        thumbnail_image_src="https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1105420/capsule_616x353.jpg?t=1700810767",
    ),
    Episode(
        episode_id=15,
        film_season_id=4,
        episode_number=4,
        episode_title="Tập 4",
        thumbnail_image_src="https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1105420/capsule_616x353.jpg?t=1700810767",
    ),
    Episode(
        episode_id=16,
        film_season_id=5,
        episode_number=1,
        episode_title="Tập 1",
        thumbnail_image_src="https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1105420/capsule_616x353.jpg?t=1700810767",
    ),
    Episode(
        episode_id=17,
        film_season_id=5,
        episode_number=2,
        episode_title="Tập 2",
        thumbnail_image_src="https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1105420/capsule_616x353.jpg?t=1700810767",
    ),
    Episode(
        episode_id=18,
        film_season_id=5,
        episode_number=3,
        episode_title="Tập 3",
        thumbnail_image_src="https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1105420/capsule_616x353.jpg?t=1700810767",
    ),
    Episode(
        episode_id=19,
        film_season_id=6,
        episode_number=1,
        episode_title="Tập 1",
        thumbnail_image_src="https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1105420/capsule_616x353.jpg?t=1700810767",
    ),
    Episode(
        episode_id=20,
        film_season_id=6,
        episode_number=2,
        episode_title="Tập 2",
        thumbnail_image_src="https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1105420/capsule_616x353.jpg?t=1700810767",
    ),
    Episode(
        episode_id=21,
        film_season_id=6,
        episode_number=3,
        episode_title="Tập 3",
        thumbnail_image_src="https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1105420/capsule_616x353.jpg?t=1700810767",
    ),
    Episode(
        episode_id=22,
        film_season_id=6,
        episode_number=4,
        episode_title="Tập 4",
        thumbnail_image_src="https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1105420/capsule_616x353.jpg?t=1700810767",
    ),
    Episode(
        episode_id=23,
        film_season_id=7,
        episode_number=1,
        episode_title="Tập 1",
        thumbnail_image_src="https://res.klook.com/image/upload/u_activities:hnnmfj2oqtp1azxoh1l3,w_1.0,ar_4:3,c_scale,e_blur:10000/c_fill,w_750,h_500/q_80/w_80,x_15,y_15,g_south_west,l_Klook_water_br_trans_yhcmh3/activities/hnnmfj2oqtp1azxoh1l3.jpg",
    ),
    Episode(
        episode_id=24,
        film_season_id=7,
        episode_number=2,
        episode_title="Tập 2",
        thumbnail_image_src="https://res.klook.com/image/upload/u_activities:hnnmfj2oqtp1azxoh1l3,w_1.0,ar_4:3,c_scale,e_blur:10000/c_fill,w_750,h_500/q_80/w_80,x_15,y_15,g_south_west,l_Klook_water_br_trans_yhcmh3/activities/hnnmfj2oqtp1azxoh1l3.jpg",
    ),
    Episode(
        episode_id=25,
        film_season_id=7,
        episode_number=3,
        episode_title="Tập 3",
        thumbnail_image_src="https://res.klook.com/image/upload/u_activities:hnnmfj2oqtp1azxoh1l3,w_1.0,ar_4:3,c_scale,e_blur:10000/c_fill,w_750,h_500/q_80/w_80,x_15,y_15,g_south_west,l_Klook_water_br_trans_yhcmh3/activities/hnnmfj2oqtp1azxoh1l3.jpg",
    ),
    Episode(
        episode_id=26,
        film_season_id=7,
        episode_number=4,
        episode_title="Tập 4",
        thumbnail_image_src="https://res.klook.com/image/upload/u_activities:hnnmfj2oqtp1azxoh1l3,w_1.0,ar_4:3,c_scale,e_blur:10000/c_fill,w_750,h_500/q_80/w_80,x_15,y_15,g_south_west,l_Klook_water_br_trans_yhcmh3/activities/hnnmfj2oqtp1azxoh1l3.jpg",
    ),
    Episode(
        episode_id=27,
        film_season_id=8,
        episode_number=1,
        episode_title="Tập 1",
        thumbnail_image_src="https://res.klook.com/image/upload/u_activities:hnnmfj2oqtp1azxoh1l3,w_1.0,ar_4:3,c_scale,e_blur:10000/c_fill,w_750,h_500/q_80/w_80,x_15,y_15,g_south_west,l_Klook_water_br_trans_yhcmh3/activities/hnnmfj2oqtp1azxoh1l3.jpg",
    ),
    Episode(
        episode_id=28,
        film_season_id=8,
        episode_number=2,
        episode_title="Tập 2",
        thumbnail_image_src="https://res.klook.com/image/upload/u_activities:hnnmfj2oqtp1azxoh1l3,w_1.0,ar_4:3,c_scale,e_blur:10000/c_fill,w_750,h_500/q_80/w_80,x_15,y_15,g_south_west,l_Klook_water_br_trans_yhcmh3/activities/hnnmfj2oqtp1azxoh1l3.jpg",
    ),
    Episode(
        episode_id=29,
        film_season_id=8,
        episode_number=3,
        episode_title="Tập 3",
        thumbnail_image_src="https://res.klook.com/image/upload/u_activities:hnnmfj2oqtp1azxoh1l3,w_1.0,ar_4:3,c_scale,e_blur:10000/c_fill,w_750,h_500/q_80/w_80,x_15,y_15,g_south_west,l_Klook_water_br_trans_yhcmh3/activities/hnnmfj2oqtp1azxoh1l3.jpg",
    ),
    Episode(
        episode_id=30,
        film_season_id=8,
        episode_number=4,
        episode_title="Tập 4",
        thumbnail_image_src="https://res.klook.com/image/upload/u_activities:hnnmfj2oqtp1azxoh1l3,w_1.0,ar_4:3,c_scale,e_blur:10000/c_fill,w_750,h_500/q_80/w_80,x_15,y_15,g_south_west,l_Klook_water_br_trans_yhcmh3/activities/hnnmfj2oqtp1azxoh1l3.jpg",
    ),
    Episode(
        episode_id=31,
        film_season_id=9,
        episode_number=1,
        episode_title="Tập 1",
        thumbnail_image_src="https://res.klook.com/image/upload/u_activities:hnnmfj2oqtp1azxoh1l3,w_1.0,ar_4:3,c_scale,e_blur:10000/c_fill,w_750,h_500/q_80/w_80,x_15,y_15,g_south_west,l_Klook_water_br_trans_yhcmh3/activities/hnnmfj2oqtp1azxoh1l3.jpg",
    ),
    Episode(
        episode_id=32,
        film_season_id=9,
        episode_number=2,
        episode_title="Tập 2",
        thumbnail_image_src="https://res.klook.com/image/upload/u_activities:hnnmfj2oqtp1azxoh1l3,w_1.0,ar_4:3,c_scale,e_blur:10000/c_fill,w_750,h_500/q_80/w_80,x_15,y_15,g_south_west,l_Klook_water_br_trans_yhcmh3/activities/hnnmfj2oqtp1azxoh1l3.jpg",
    ),
    Episode(
        episode_id=33,
        film_season_id=9,
        episode_number=3,
        episode_title="Tập 3",
        thumbnail_image_src="https://res.klook.com/image/upload/u_activities:hnnmfj2oqtp1azxoh1l3,w_1.0,ar_4:3,c_scale,e_blur:10000/c_fill,w_750,h_500/q_80/w_80,x_15,y_15,g_south_west,l_Klook_water_br_trans_yhcmh3/activities/hnnmfj2oqtp1azxoh1l3.jpg",
    ),
    Episode(
        episode_id=34,
        film_season_id=10,
        episode_number=1,
        episode_title="Tập 1",
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPviGBB6hW_MEzfW2pj7-qgbaxP3_hPVKA8A&s",
    ),
    Episode(
        episode_id=35,
        film_season_id=10,
        episode_number=2,
        episode_title="Tập 2",
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPviGBB6hW_MEzfW2pj7-qgbaxP3_hPVKA8A&s",
    ),
    Episode(
        episode_id=36,
        film_season_id=10,
        episode_number=3,
        episode_title="Tập 3",
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPviGBB6hW_MEzfW2pj7-qgbaxP3_hPVKA8A&s",
    ),
    Episode(
        episode_id=37,
        film_season_id=11,
        episode_number=1,
        episode_title="Tập 1",
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPviGBB6hW_MEzfW2pj7-qgbaxP3_hPVKA8A&s",
    ),
    Episode(
        episode_id=38,
        film_season_id=11,
        episode_number=2,
        episode_title="Tập 2",
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPviGBB6hW_MEzfW2pj7-qgbaxP3_hPVKA8A&s",
    ),
    Episode(
        episode_id=39,
        film_season_id=11,
        episode_number=3,
        episode_title="Tập 3",
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPviGBB6hW_MEzfW2pj7-qgbaxP3_hPVKA8A&s",
    ),
    Episode(
        episode_id=40,
        film_season_id=11,
        episode_number=4,
        episode_title="Tập 4",
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPviGBB6hW_MEzfW2pj7-qgbaxP3_hPVKA8A&s",
    ),
    Episode(
        episode_id=41,
        film_season_id=12,
        episode_number=1,
        episode_title="Tập 1",
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPviGBB6hW_MEzfW2pj7-qgbaxP3_hPVKA8A&s",
    ),
    Episode(
        episode_id=42,
        film_season_id=12,
        episode_number=2,
        episode_title="Tập 2",
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPviGBB6hW_MEzfW2pj7-qgbaxP3_hPVKA8A&s",
    ),
    Episode(
        episode_id=43,
        film_season_id=12,
        episode_number=3,
        episode_title="Tập 3",
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPviGBB6hW_MEzfW2pj7-qgbaxP3_hPVKA8A&s",
    ),
    Episode(
        episode_id=44,
        film_season_id=12,
        episode_number=4,
        episode_title="Tập 4",
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPviGBB6hW_MEzfW2pj7-qgbaxP3_hPVKA8A&s",
    ),
    Episode(
        episode_id=45,
        film_season_id=13,
        episode_number=1,
        episode_title="Tập 1",
        thumbnail_image_src="https://images.thedirect.com/media/article_full/mandalorian-pedro-pascal-season-3.jpg",
    ),
    Episode(
        episode_id=46,
        film_season_id=13,
        episode_number=2,
        episode_title="Tập 2",
        thumbnail_image_src="https://images.thedirect.com/media/article_full/mandalorian-pedro-pascal-season-3.jpg",
    ),
    Episode(
        episode_id=47,
        film_season_id=13,
        episode_number=3,
        episode_title="Tập 3",
        thumbnail_image_src="https://images.thedirect.com/media/article_full/mandalorian-pedro-pascal-season-3.jpg",
    ),
    Episode(
        episode_id=48,
        film_season_id=14,
        episode_number=1,
        episode_title="Tập 1",
        thumbnail_image_src="https://images.thedirect.com/media/article_full/mandalorian-pedro-pascal-season-3.jpg",
    ),
    Episode(
        episode_id=49,
        film_season_id=14,
        episode_number=2,
        episode_title="Tập 2",
        thumbnail_image_src="https://images.thedirect.com/media/article_full/mandalorian-pedro-pascal-season-3.jpg",
    ),
    Episode(
        episode_id=50,
        film_season_id=14,
        episode_number=3,
        episode_title="Tập 3",
        thumbnail_image_src="https://images.thedirect.com/media/article_full/mandalorian-pedro-pascal-season-3.jpg",
    ),
    Episode(
        episode_id=51,
        film_season_id=14,
        episode_number=4,
        episode_title="Tập 4",
        thumbnail_image_src="https://images.thedirect.com/media/article_full/mandalorian-pedro-pascal-season-3.jpg",
    ),
    Episode(
        episode_id=52,
        film_season_id=15,
        episode_number=1,
        episode_title="Tập 1",
        thumbnail_image_src="https://images.thedirect.com/media/article_full/mandalorian-pedro-pascal-season-3.jpg",
    ),
    Episode(
        episode_id=53,
        film_season_id=15,
        episode_number=2,
        episode_title="Tập 2",
        thumbnail_image_src="https://images.thedirect.com/media/article_full/mandalorian-pedro-pascal-season-3.jpg",
    ),
    Episode(
        episode_id=54,
        film_season_id=15,
        episode_number=3,
        episode_title="Tập 3",
        thumbnail_image_src="https://images.thedirect.com/media/article_full/mandalorian-pedro-pascal-season-3.jpg",
    ),
    Episode(
        episode_id=55,
        film_season_id=16,
        episode_number=1,
        episode_title="Tập 1",
        thumbnail_image_src="https://resizing.flixster.com/c5XeWe5kfWQjpGyL2-fzQY4Upb4=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p13398828_b_h10_aa.jpg",
    ),
    Episode(
        episode_id=56,
        film_season_id=16,
        episode_number=2,
        episode_title="Tập 2",
        thumbnail_image_src="https://resizing.flixster.com/c5XeWe5kfWQjpGyL2-fzQY4Upb4=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p13398828_b_h10_aa.jpg",
    ),
    Episode(
        episode_id=57,
        film_season_id=16,
        episode_number=3,
        episode_title="Tập 3",
        thumbnail_image_src="https://resizing.flixster.com/c5XeWe5kfWQjpGyL2-fzQY4Upb4=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p13398828_b_h10_aa.jpg",
    ),
    Episode(
        episode_id=58,
        film_season_id=17,
        episode_number=1,
        episode_title="Tập 1",
        thumbnail_image_src="https://resizing.flixster.com/c5XeWe5kfWQjpGyL2-fzQY4Upb4=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p13398828_b_h10_aa.jpg",
    ),
    Episode(
        episode_id=59,
        film_season_id=17,
        episode_number=2,
        episode_title="Tập 2",
        thumbnail_image_src="https://resizing.flixster.com/c5XeWe5kfWQjpGyL2-fzQY4Upb4=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p13398828_b_h10_aa.jpg",
    ),
    Episode(
        episode_id=60,
        film_season_id=17,
        episode_number=3,
        episode_title="Tập 3",
        thumbnail_image_src="https://resizing.flixster.com/c5XeWe5kfWQjpGyL2-fzQY4Upb4=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p13398828_b_h10_aa.jpg",
    ),
    Episode(
        episode_id=61,
        film_season_id=18,
        episode_number=1,
        episode_title="Tập 1",
        thumbnail_image_src="https://resizing.flixster.com/c5XeWe5kfWQjpGyL2-fzQY4Upb4=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p13398828_b_h10_aa.jpg",
    ),
    Episode(
        episode_id=62,
        film_season_id=18,
        episode_number=2,
        episode_title="Tập 2",
        thumbnail_image_src="https://resizing.flixster.com/c5XeWe5kfWQjpGyL2-fzQY4Upb4=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p13398828_b_h10_aa.jpg",
    ),
    Episode(
        episode_id=63,
        film_season_id=18,
        episode_number=3,
        episode_title="Tập 3",
        thumbnail_image_src="https://resizing.flixster.com/c5XeWe5kfWQjpGyL2-fzQY4Upb4=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p13398828_b_h10_aa.jpg",
    ),
    Episode(
        episode_id=64,
        film_season_id=18,
        episode_number=4,
        episode_title="Tập 4",
        thumbnail_image_src="https://resizing.flixster.com/c5XeWe5kfWQjpGyL2-fzQY4Upb4=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p13398828_b_h10_aa.jpg",
    ),
    Episode(
        episode_id=65,
        film_season_id=19,
        episode_number=1,
        episode_title="Tập 1",
        thumbnail_image_src="https://uniathenaprods3.uniathena.com/s3fs-public/insights-article/seriesreview-e2-80-9cfriends-e2-80-9d_0.jpg",
    ),
    Episode(
        episode_id=66,
        film_season_id=19,
        episode_number=2,
        episode_title="Tập 2",
        thumbnail_image_src="https://uniathenaprods3.uniathena.com/s3fs-public/insights-article/seriesreview-e2-80-9cfriends-e2-80-9d_0.jpg",
    ),
    Episode(
        episode_id=67,
        film_season_id=19,
        episode_number=3,
        episode_title="Tập 3",
        thumbnail_image_src="https://uniathenaprods3.uniathena.com/s3fs-public/insights-article/seriesreview-e2-80-9cfriends-e2-80-9d_0.jpg",
    ),
    Episode(
        episode_id=68,
        film_season_id=20,
        episode_number=1,
        episode_title="Tập 1",
        thumbnail_image_src="https://uniathenaprods3.uniathena.com/s3fs-public/insights-article/seriesreview-e2-80-9cfriends-e2-80-9d_0.jpg",
    ),
    Episode(
        episode_id=69,
        film_season_id=20,
        episode_number=2,
        episode_title="Tập 2",
        thumbnail_image_src="https://uniathenaprods3.uniathena.com/s3fs-public/insights-article/seriesreview-e2-80-9cfriends-e2-80-9d_0.jpg",
    ),
    Episode(
        episode_id=70,
        film_season_id=20,
        episode_number=3,
        episode_title="Tập 3",
        thumbnail_image_src="https://uniathenaprods3.uniathena.com/s3fs-public/insights-article/seriesreview-e2-80-9cfriends-e2-80-9d_0.jpg",
    ),
    Episode(
        episode_id=71,
        film_season_id=20,
        episode_number=4,
        episode_title="Tập 4",
        thumbnail_image_src="https://uniathenaprods3.uniathena.com/s3fs-public/insights-article/seriesreview-e2-80-9cfriends-e2-80-9d_0.jpg",
    ),
    Episode(
        episode_id=72,
        film_season_id=21,
        episode_number=1,
        episode_title="Tập 1",
        thumbnail_image_src="https://uniathenaprods3.uniathena.com/s3fs-public/insights-article/seriesreview-e2-80-9cfriends-e2-80-9d_0.jpg",
    ),
    Episode(
        episode_id=73,
        film_season_id=21,
        episode_number=2,
        episode_title="Tập 2",
        thumbnail_image_src="https://uniathenaprods3.uniathena.com/s3fs-public/insights-article/seriesreview-e2-80-9cfriends-e2-80-9d_0.jpg",
    ),
    Episode(
        episode_id=74,
        film_season_id=21,
        episode_number=3,
        episode_title="Tập 3",
        thumbnail_image_src="https://uniathenaprods3.uniathena.com/s3fs-public/insights-article/seriesreview-e2-80-9cfriends-e2-80-9d_0.jpg",
    ),
    Episode(
        episode_id=75,
        film_season_id=22,
        episode_number=1,
        episode_title="Tập 1",
        thumbnail_image_src="https://resizing.flixster.com/8nJUFmVSfYuWfAA6LVmGqJc4UH8=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p8992561_b_h10_aa.jpg",
    ),
    Episode(
        episode_id=76,
        film_season_id=22,
        episode_number=2,
        episode_title="Tập 2",
        thumbnail_image_src="https://resizing.flixster.com/8nJUFmVSfYuWfAA6LVmGqJc4UH8=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p8992561_b_h10_aa.jpg",
    ),
    Episode(
        episode_id=77,
        film_season_id=22,
        episode_number=3,
        episode_title="Tập 3",
        thumbnail_image_src="https://resizing.flixster.com/8nJUFmVSfYuWfAA6LVmGqJc4UH8=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p8992561_b_h10_aa.jpg",
    ),
    Episode(
        episode_id=78,
        film_season_id=22,
        episode_number=4,
        episode_title="Tập 4",
        thumbnail_image_src="https://resizing.flixster.com/8nJUFmVSfYuWfAA6LVmGqJc4UH8=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p8992561_b_h10_aa.jpg",
    ),
    Episode(
        episode_id=79,
        film_season_id=23,
        episode_number=1,
        episode_title="Tập 1",
        thumbnail_image_src="https://resizing.flixster.com/8nJUFmVSfYuWfAA6LVmGqJc4UH8=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p8992561_b_h10_aa.jpg",
    ),
    Episode(
        episode_id=80,
        film_season_id=23,
        episode_number=2,
        episode_title="Tập 2",
        thumbnail_image_src="https://resizing.flixster.com/8nJUFmVSfYuWfAA6LVmGqJc4UH8=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p8992561_b_h10_aa.jpg",
    ),
    Episode(
        episode_id=81,
        film_season_id=23,
        episode_number=3,
        episode_title="Tập 3",
        thumbnail_image_src="https://resizing.flixster.com/8nJUFmVSfYuWfAA6LVmGqJc4UH8=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p8992561_b_h10_aa.jpg",
    ),
    Episode(
        episode_id=82,
        film_season_id=24,
        episode_number=1,
        episode_title="Tập 1",
        thumbnail_image_src="https://resizing.flixster.com/8nJUFmVSfYuWfAA6LVmGqJc4UH8=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p8992561_b_h10_aa.jpg",
    ),
    Episode(
        episode_id=83,
        film_season_id=24,
        episode_number=2,
        episode_title="Tập 2",
        thumbnail_image_src="https://resizing.flixster.com/8nJUFmVSfYuWfAA6LVmGqJc4UH8=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p8992561_b_h10_aa.jpg",
    ),
    Episode(
        episode_id=84,
        film_season_id=24,
        episode_number=3,
        episode_title="Tập 3",
        thumbnail_image_src="https://resizing.flixster.com/8nJUFmVSfYuWfAA6LVmGqJc4UH8=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p8992561_b_h10_aa.jpg",
    ),
    Episode(
        episode_id=85,
        film_season_id=24,
        episode_number=4,
        episode_title="Tập 4",
        thumbnail_image_src="https://resizing.flixster.com/8nJUFmVSfYuWfAA6LVmGqJc4UH8=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p8992561_b_h10_aa.jpg",
    ),
    Episode(
        episode_id=86,
        film_season_id=25,
        episode_number=1,
        episode_title="Tập 1",
        thumbnail_image_src="https://upload.wikimedia.org/wikipedia/en/2/28/Westworld_season_1.png",
    ),
    Episode(
        episode_id=87,
        film_season_id=25,
        episode_number=2,
        episode_title="Tập 2",
        thumbnail_image_src="https://upload.wikimedia.org/wikipedia/en/2/28/Westworld_season_1.png",
    ),
    Episode(
        episode_id=88,
        film_season_id=25,
        episode_number=3,
        episode_title="Tập 3",
        thumbnail_image_src="https://upload.wikimedia.org/wikipedia/en/2/28/Westworld_season_1.png",
    ),
    Episode(
        episode_id=89,
        film_season_id=25,
        episode_number=4,
        episode_title="Tập 4",
        thumbnail_image_src="https://upload.wikimedia.org/wikipedia/en/2/28/Westworld_season_1.png",
    ),
    Episode(
        episode_id=90,
        film_season_id=26,
        episode_number=1,
        episode_title="Tập 1",
        thumbnail_image_src="https://upload.wikimedia.org/wikipedia/en/2/28/Westworld_season_1.png",
    ),
    Episode(
        episode_id=91,
        film_season_id=26,
        episode_number=2,
        episode_title="Tập 2",
        thumbnail_image_src="https://upload.wikimedia.org/wikipedia/en/2/28/Westworld_season_1.png",
    ),
    Episode(
        episode_id=92,
        film_season_id=26,
        episode_number=3,
        episode_title="Tập 3",
        thumbnail_image_src="https://upload.wikimedia.org/wikipedia/en/2/28/Westworld_season_1.png",
    ),
    Episode(
        episode_id=93,
        film_season_id=27,
        episode_number=1,
        episode_title="Tập 1",
        thumbnail_image_src="https://upload.wikimedia.org/wikipedia/en/2/28/Westworld_season_1.png",
    ),
    Episode(
        episode_id=94,
        film_season_id=27,
        episode_number=2,
        episode_title="Tập 2",
        thumbnail_image_src="https://upload.wikimedia.org/wikipedia/en/2/28/Westworld_season_1.png",
    ),
    Episode(
        episode_id=95,
        film_season_id=27,
        episode_number=3,
        episode_title="Tập 3",
        thumbnail_image_src="https://upload.wikimedia.org/wikipedia/en/2/28/Westworld_season_1.png",
    ),
    Episode(
        episode_id=96,
        film_season_id=27,
        episode_number=4,
        episode_title="Tập 4",
        thumbnail_image_src="https://upload.wikimedia.org/wikipedia/en/2/28/Westworld_season_1.png",
    ),
    Episode(
        episode_id=97,
        film_season_id=28,
        episode_number=1,
        episode_title="Tập 1",
        thumbnail_image_src="https://upload.wikimedia.org/wikipedia/en/a/ae/The_Office_Season_8.jpg",
    ),
    Episode(
        episode_id=98,
        film_season_id=28,
        episode_number=2,
        episode_title="Tập 2",
        thumbnail_image_src="https://upload.wikimedia.org/wikipedia/en/a/ae/The_Office_Season_8.jpg",
    ),
    Episode(
        episode_id=99,
        film_season_id=28,
        episode_number=3,
        episode_title="Tập 3",
        thumbnail_image_src="https://upload.wikimedia.org/wikipedia/en/a/ae/The_Office_Season_8.jpg",
    ),
    Episode(
        episode_id=100,
        film_season_id=29,
        episode_number=1,
        episode_title="Tập 1",
        thumbnail_image_src="https://upload.wikimedia.org/wikipedia/en/a/ae/The_Office_Season_8.jpg",
    ),
    Episode(
        episode_id=101,
        film_season_id=29,
        episode_number=2,
        episode_title="Tập 2",
        thumbnail_image_src="https://upload.wikimedia.org/wikipedia/en/a/ae/The_Office_Season_8.jpg",
    ),
    Episode(
        episode_id=102,
        film_season_id=29,
        episode_number=3,
        episode_title="Tập 3",
        thumbnail_image_src="https://upload.wikimedia.org/wikipedia/en/a/ae/The_Office_Season_8.jpg",
    ),
    Episode(
        episode_id=103,
        film_season_id=29,
        episode_number=4,
        episode_title="Tập 4",
        thumbnail_image_src="https://upload.wikimedia.org/wikipedia/en/a/ae/The_Office_Season_8.jpg",
    ),
    Episode(
        episode_id=104,
        film_season_id=30,
        episode_number=1,
        episode_title="Tập 1",
        thumbnail_image_src="https://upload.wikimedia.org/wikipedia/en/a/ae/The_Office_Season_8.jpg",
    ),
    Episode(
        episode_id=105,
        film_season_id=30,
        episode_number=2,
        episode_title="Tập 2",
        thumbnail_image_src="https://upload.wikimedia.org/wikipedia/en/a/ae/The_Office_Season_8.jpg",
    ),
    Episode(
        episode_id=106,
        film_season_id=30,
        episode_number=3,
        episode_title="Tập 3",
        thumbnail_image_src="https://upload.wikimedia.org/wikipedia/en/a/ae/The_Office_Season_8.jpg",
    ),
    Episode(
        episode_id=107,
        film_season_id=31,
        episode_number=1,
        episode_title="Tập 1",
        thumbnail_image_src="https://touchcinema.com/storage/phim-ke-danh-cap-giac-mo/phim-ke-danh-cap-giac-mo.jpg",
    ),
    Episode(
        episode_id=108,
        film_season_id=31,
        episode_number=2,
        episode_title="Tập 2",
        thumbnail_image_src="https://touchcinema.com/storage/phim-ke-danh-cap-giac-mo/phim-ke-danh-cap-giac-mo.jpg",
    ),
    Episode(
        episode_id=109,
        film_season_id=31,
        episode_number=3,
        episode_title="Tập 3",
        thumbnail_image_src="https://touchcinema.com/storage/phim-ke-danh-cap-giac-mo/phim-ke-danh-cap-giac-mo.jpg",
    ),
    Episode(
        episode_id=110,
        film_season_id=31,
        episode_number=4,
        episode_title="Tập 4",
        thumbnail_image_src="https://touchcinema.com/storage/phim-ke-danh-cap-giac-mo/phim-ke-danh-cap-giac-mo.jpg",
    ),
    Episode(
        episode_id=111,
        film_season_id=32,
        episode_number=1,
        episode_title="Tập 1",
        thumbnail_image_src="https://substackcdn.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fbucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com%2Fpublic%2Fimages%2F58af398c-d206-446e-a587-bfff4449d94c_704x396.jpeg",
    ),
    Episode(
        episode_id=112,
        film_season_id=32,
        episode_number=2,
        episode_title="Tập 2",
        thumbnail_image_src="https://substackcdn.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fbucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com%2Fpublic%2Fimages%2F58af398c-d206-446e-a587-bfff4449d94c_704x396.jpeg",
    ),
    Episode(
        episode_id=113,
        film_season_id=32,
        episode_number=3,
        episode_title="Tập 3",
        thumbnail_image_src="https://substackcdn.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fbucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com%2Fpublic%2Fimages%2F58af398c-d206-446e-a587-bfff4449d94c_704x396.jpeg",
    ),
    Episode(
        episode_id=114,
        film_season_id=33,
        episode_number=1,
        episode_title="Tập 1",
        thumbnail_image_src="https://d1jqhvzwrc220t.cloudfront.net/media/blog/800x450_5.webp",
    ),
    Episode(
        episode_id=115,
        film_season_id=33,
        episode_number=2,
        episode_title="Tập 2",
        thumbnail_image_src="https://d1jqhvzwrc220t.cloudfront.net/media/blog/800x450_5.webp",
    ),
    Episode(
        episode_id=116,
        film_season_id=33,
        episode_number=3,
        episode_title="Tập 3",
        thumbnail_image_src="https://d1jqhvzwrc220t.cloudfront.net/media/blog/800x450_5.webp",
    ),
    Episode(
        episode_id=117,
        film_season_id=34,
        episode_number=1,
        episode_title="Tập 1",
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_WiCDscohAM2TnmUX65VwEYBbO-YZ0IvSA2hT9ofyfMHTVnUwXX5hr5h_BipI24_Zu0Q&usqp=CAU",
    ),
    Episode(
        episode_id=118,
        film_season_id=34,
        episode_number=2,
        episode_title="Tập 2",
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_WiCDscohAM2TnmUX65VwEYBbO-YZ0IvSA2hT9ofyfMHTVnUwXX5hr5h_BipI24_Zu0Q&usqp=CAU",
    ),
    Episode(
        episode_id=119,
        film_season_id=34,
        episode_number=3,
        episode_title="Tập 3",
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_WiCDscohAM2TnmUX65VwEYBbO-YZ0IvSA2hT9ofyfMHTVnUwXX5hr5h_BipI24_Zu0Q&usqp=CAU",
    ),
    Episode(
        episode_id=120,
        film_season_id=35,
        episode_number=1,
        episode_title="Tập 1",
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQO_TClh7CqMdS2ky-YJTkXzZZtcS1OMejeDs9T26C0YBJUMb_t3HSPRpqVz-ag8NBUYDY&usqp=CAU",
    ),
    Episode(
        episode_id=121,
        film_season_id=35,
        episode_number=2,
        episode_title="Tập 2",
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQO_TClh7CqMdS2ky-YJTkXzZZtcS1OMejeDs9T26C0YBJUMb_t3HSPRpqVz-ag8NBUYDY&usqp=CAU",
    ),
    Episode(
        episode_id=122,
        film_season_id=35,
        episode_number=3,
        episode_title="Tập 3",
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQO_TClh7CqMdS2ky-YJTkXzZZtcS1OMejeDs9T26C0YBJUMb_t3HSPRpqVz-ag8NBUYDY&usqp=CAU",
    ),
    Episode(
        episode_id=123,
        film_season_id=36,
        episode_number=1,
        episode_title="Tập 1",
        thumbnail_image_src="https://cdn.quotesgram.com/img/21/93/1351081511-1994_forrest_gump_1.jpg",
    ),
    Episode(
        episode_id=124,
        film_season_id=36,
        episode_number=2,
        episode_title="Tập 2",
        thumbnail_image_src="https://cdn.quotesgram.com/img/21/93/1351081511-1994_forrest_gump_1.jpg",
    ),
    Episode(
        episode_id=125,
        film_season_id=36,
        episode_number=3,
        episode_title="Tập 3",
        thumbnail_image_src="https://cdn.quotesgram.com/img/21/93/1351081511-1994_forrest_gump_1.jpg",
    ),
    Episode(
        episode_id=126,
        film_season_id=37,
        episode_number=1,
        episode_title="Tập 1",
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQm_-j_N9fIpunypxUaOK-XHj51kxiEsxINGA&s",
    ),
    Episode(
        episode_id=127,
        film_season_id=37,
        episode_number=2,
        episode_title="Tập 2",
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQm_-j_N9fIpunypxUaOK-XHj51kxiEsxINGA&s",
    ),
    Episode(
        episode_id=128,
        film_season_id=37,
        episode_number=3,
        episode_title="Tập 3",
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQm_-j_N9fIpunypxUaOK-XHj51kxiEsxINGA&s",
    ),
    Episode(
        episode_id=129,
        film_season_id=37,
        episode_number=4,
        episode_title="Tập 4",
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQm_-j_N9fIpunypxUaOK-XHj51kxiEsxINGA&s",
    ),
    Episode(
        episode_id=130,
        film_season_id=38,
        episode_number=1,
        episode_title="Tập 1",
        thumbnail_image_src="https://mir-s3-cdn-cf.behance.net/projects/404/b96064178494413.Y3JvcCwxNDk4LDExNzEsMCw4NzU.png",
    ),
    Episode(
        episode_id=131,
        film_season_id=38,
        episode_number=2,
        episode_title="Tập 2",
        thumbnail_image_src="https://mir-s3-cdn-cf.behance.net/projects/404/b96064178494413.Y3JvcCwxNDk4LDExNzEsMCw4NzU.png",
    ),
    Episode(
        episode_id=132,
        film_season_id=38,
        episode_number=3,
        episode_title="Tập 3",
        thumbnail_image_src="https://mir-s3-cdn-cf.behance.net/projects/404/b96064178494413.Y3JvcCwxNDk4LDExNzEsMCw4NzU.png",
    ),
    Episode(
        episode_id=133,
        film_season_id=38,
        episode_number=4,
        episode_title="Tập 4",
        thumbnail_image_src="https://mir-s3-cdn-cf.behance.net/projects/404/b96064178494413.Y3JvcCwxNDk4LDExNzEsMCw4NzU.png",
    ),
    Episode(
        episode_id=134,
        film_season_id=39,
        episode_number=1,
        episode_title="Tập 1",
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLElDkJXrpyc09Z28q15C0olBZvvpAwR9_ZQ&s",
    ),
    Episode(
        episode_id=135,
        film_season_id=39,
        episode_number=2,
        episode_title="Tập 2",
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLElDkJXrpyc09Z28q15C0olBZvvpAwR9_ZQ&s",
    ),
    Episode(
        episode_id=136,
        film_season_id=39,
        episode_number=3,
        episode_title="Tập 3",
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLElDkJXrpyc09Z28q15C0olBZvvpAwR9_ZQ&s",
    ),
    Episode(
        episode_id=137,
        film_season_id=39,
        episode_number=4,
        episode_title="Tập 4",
        thumbnail_image_src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLElDkJXrpyc09Z28q15C0olBZvvpAwR9_ZQ&s",
    ),
    Episode(
        episode_id=138,
        film_season_id=40,
        episode_number=1,
        episode_title="Tập 1",
        thumbnail_image_src="https://lecinemaparadiso.co.uk/uploads/THE%20SHAWSHANK%20REDEMPTION%20image.jpg",
    ),
    Episode(
        episode_id=139,
        film_season_id=40,
        episode_number=2,
        episode_title="Tập 2",
        thumbnail_image_src="https://lecinemaparadiso.co.uk/uploads/THE%20SHAWSHANK%20REDEMPTION%20image.jpg",
    ),
    Episode(
        episode_id=140,
        film_season_id=40,
        episode_number=3,
        episode_title="Tập 3",
        thumbnail_image_src="https://lecinemaparadiso.co.uk/uploads/THE%20SHAWSHANK%20REDEMPTION%20image.jpg",
    ),
]

"""
# Initialize the episodes list
# episodes: List[Episode] = []

# Counter for episode IDs
episode_id_counter = 1

# Open the file for writing
with open("output.txt", "w", encoding="utf-8") as file:
    # Loop through each season and generate episodes
    for season in seasons:
        # Determine the number of episodes (between 3 and 4)
        num_episodes = random.randint(3, 4)
        
        for episode_number in range(1, num_episodes + 1):
            episode = Episode(
                episode_id=episode_id_counter,
                film_season_id=season.season_id,
                episode_number=episode_number,
                episode_title=f"Tập {episode_number}",
                thumbnail_image_src=season.thumbnail_image_src
            )
            # episodes.append(episode)
            
            # Write the episode to the file in the desired format
            file.write(f"Episode( episode_id={episode.episode_id}, film_season_id={episode.film_season_id}, episode_number={episode.episode_number}, episode_title='{episode.episode_title}', thumbnail_image_src='{episode.thumbnail_image_src}' ),\n")
            
            # Increment the episode ID counter
            episode_id_counter += 1
"""
